version: "3.9"
services:
  fe-dapung:
    container_name: dockerDapungFe
    build:
      context: .
      args:
        - PORT=${PORT}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_PUBLIC_AWAL_WAKTU_PERTAMA=${NEXT_PUBLIC_AWAL_WAKTU_PERTAMA}
        - NEXT_PUBLIC_AKHIR_WAKTU_PERTAMA=${NEXT_PUBLIC_AKHIR_WAKTU_PERTAMA}
        - NEXT_PUBLIC_AWAL_WAKTU_KEDUA=${NEXT_PUBLIC_AWAL_WAKTU_KEDUA}
        - NEXT_PUBLIC_AKHIR_WAKTU_KEDUA=${NEXT_PUBLIC_AKHIR_WAKTU_KEDUA}
    init: true
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
