services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-dapung
    image: myapp:latest
    env_file:
      - .env
    ports:
      - "${PORT}:5006"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dapung-network

  db:
    container_name: mysql-dapung
    image: mysql:8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_HOST=%
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dapung-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  mysql_data:

networks:
  dapung-network:
    driver: bridge